config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  get "how-it-works", to: "pages#how_it_works", as: "how_it_works"
  get "about", to: "pages#about", as: "about"
  get "menus", to: "pages#menus", as: "menus"

  resources :contacts, only: [:new, :create]

  namespace :admin do
    root "pages#index"
    resources :pages
    resources :users
    resources :categories do
      resources :menu_items
    end
    post "update-weights", to: "weights#update", as: "weights_update"
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name

  has_many :menu_items, -> { order(:weight) }, dependent: :destroy
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  after_create :notify_admin

  validates_presence_of :name, :email, :message

  private

  def notify_admin
    # Send an email here
  end
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :name
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessor :tagline, :quote, :quote_author

  has_attached_file :image,
                    storage: :s3,
                    styles: { thumb: "150x150>" },
                    s3_credentials: Proc.new{|a| a.instance.s3_credentials }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def s3_credentials
    { bucket: ENV['AWS_S3_BUCKET'], access_key_id: ENV['AWS_S3_ACCESS_KEY'], secret_access_key: ENV['AWS_S3_SECRET_KEY'] }
  end

  def tagline
    settings["tagline"]
  end

  def quote
    settings["quote"]
  end

  def quote_author
    settings["quote_author"]
  end

  def home?
    key === "home"
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all.order(:weight)
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "Great job! Update successful."
    else
      render "new"
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: "Great job! Update successful."
    else
      render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path, notice: "Great job! Delete successful."
  end

  private

  def category_params
    params.require(:category).permit(:name, :weight)
  end
end

app/controllers/admin/menu_items_controller.rb
class Admin::MenuItemsController < AdminController
  before_filter :assign_category

  def new
    @menu_item = MenuItem.new
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def create
    @menu_item = MenuItem.new(menu_items_params.merge(category_id: @category.id))
    if @menu_item.save
      redirect_to admin_category_path(@category), notice: "Great job! Update successful."
    else
      render "new"
    end
  end

  def update
    @menu_item = MenuItem.find(params[:id])
    if @menu_item.update(menu_items_params)
      redirect_to admin_category_path(@category), notice: "Great job! Update successful."
    else
      render "edit"
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy
    redirect_to admin_category_path(@category), notice: "Great job! Delete successful."
  end

  private

  def menu_items_params
    params.require(:menu_item).permit(:name, :description, :weight)
  end

  def assign_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < AdminController
  def index
    @pages = Page.all.order(:title)
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    update_settings
    if @page.update(page_params)
      redirect_to edit_admin_page_path(@page), notice: "Great job! Update successful."
    else
      render "edit"
    end
  end

  private

  def page_params
    params.require(:page).permit!
  end

  def update_settings
    settings = {}
    settings["tagline"] = page_params["tagline"] unless page_params["tagline"].blank?
    settings["quote"] = page_params["quote"] unless page_params["quote"].blank?
    settings["quote_author"] = page_params["quote_author"] unless page_params["quote_author"].blank?
    @page.settings = settings
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.all
  end
end

app/controllers/admin/weights_controller.rb
class Admin::WeightsController < AdminController
  def update
    model = params[:model_name].constantize
    params[:models].each_pair do |id, weight|
      model.where(id: id).update_all(weight: weight)
    end
    render json: { success: true }
  rescue => e
    logger.error('Weights could not be saved.')
    logger.error(e)
    render json: { success: false}
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.new_contact(@contact).deliver_now
      redirect_to new_contact_path, notice: "Thank you! We will chat soon :)"
    else
      render "new"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page = Page.find_by(key: "home")
    @how_it_works = Page.find_by(key: "how_it_works")
    @about = Page.find_by(key: "about")
    @menus = Page.find_by(key: "menus")
  end

  def how_it_works
    @page = Page.find_by(key: "how_it_works")
  end

  def about
    @page = Page.find_by(key: "about")
  end

  def menus
    @page = Page.find_by(key: "menus")
    @categories = Category.all.order(:weight).includes(:menu_items)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''
    link_to link_text, link_path, class: class_name
  end
end

app/views/admin/categories/edit.html.erb
<h1>Edit Category: <em><%= @category.name %></em></h1>

<%= simple_form_for(["admin", @category]) do |f| %>
  <%= f.input :name %>
  <hr>
  <div class="form-group">
    <%= f.button :submit %>
    <%= link_to "Cancel", admin_categories_path, class: "btn" %>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
<h1>Categories</h1>
<%= link_to "+ New Category", new_admin_category_path %>
<hr>

<%= render "admin/shared/sort_flashes" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="sortable" data-update-url="<%= admin_weights_update_path %>" data-model-name="Category">
    <% @categories.each do |category| %>
    <tr data-id="<%= category.id %>" data-weight="<%= category.weight %>">
      <td style="width: 30px;"><span class="glyphicon glyphicon-move"></span></td>
      <td><%= category.name %></td>
      <td>
        <%= link_to "View", admin_category_path(category) %>
        <%= link_to "Edit", edit_admin_category_path(category) %>
        <%= link_to "Delete", admin_category_path(category), method: :delete, data: { confirm: "Are you sure? This will delete all associated menu items as well." }, class: "text-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= simple_form_for(["admin", @category]) do |f| %>
  <%= f.input :name %>
  <hr>
  <div class="form-group">
    <%= f.button :submit %>
    <%= link_to "Cancel", admin_categories_path, class: "btn" %>
  </div>
<% end %>

app/views/admin/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>
<%= link_to "+ New Menu Item", new_admin_category_menu_item_path(category_id: @category.id) %>
<hr>

<% if @category.menu_items.any? %>
<%= render "admin/shared/sort_flashes" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="sortable" data-update-url="<%= admin_weights_update_path %>" data-model-name="MenuItem">
    <% @category.menu_items.each do |menu_item| %>
    <tr data-id="<%= menu_item.id %>" data-weight="<%= menu_item.weight %>">
      <td style="width: 30px;"><span class="glyphicon glyphicon-move"></span></td>
      <td><%= menu_item.name %></td>
      <td>
        <%= link_to "Edit", edit_admin_category_menu_item_path(category_id: @category.id, id: menu_item) %>
        <%= link_to "Delete", admin_category_menu_item_path(category_id: @category.id, id: menu_item), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger" %>

      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  Add some menu items already!
<% end %>

app/views/admin/menu_items/edit.html.erb
<h1>Edit Menu Item: <em><%= @menu_item.name %></em></h1>
<p><strong>Category:</strong> <%= @category.name %></p>
<hr>

<%= simple_form_for(@menu_item, url: admin_category_menu_item_path(category_id: @category.id, id: @menu_item.id)) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <hr>
  <%= f.button :submit %>
  <%= link_to "Cancel", admin_category_path(@category), class: "btn" %>
<% end %>

app/views/admin/menu_items/new.html.erb
<h1>New Menu Item</h1>
<p><strong>Category:</strong> <%= @category.name %></p>
<hr>

<%= simple_form_for(@menu_item, url: admin_category_menu_items_path(category_id: @category.id)) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <hr>
  <%= f.button :submit %>
  <%= link_to "Cancel", admin_category_path(@category), class: "btn" %>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Edit Page: <em><%= @page.title %></em></h1>
<p><%= link_to "Back to Pages", admin_pages_path %></p>
<hr>

<%= simple_form_for(["admin", @page]) do |f| %>
  <%= f.input :title %>
  <%= f.input :body, input_html: { class: "editor" } unless @page.home? %>
  <%= f.input :image, as: :image, input_html: { preview_version: :thumb } unless @page.home? %>
  <%= f.input :tagline if @page.home? %>
  <%= f.input :quote if @page.home? %>
  <%= f.input :quote_author if @page.home? %>
  <hr>
  <div class="form-group">
    <%= f.button :submit %>
    <%= link_to "Cancel", admin_pages_path, class: "btn" %>
  </div>
<% end %>

app/views/admin/pages/index.html.erb
<h1>Pages</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td><%= link_to "Edit", edit_admin_page_path(page) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/shared/_sort_flashes.html.erb
<div class="alert alert-success sort-success" style="display: none;">Position successfully updated :)</div>
<div class="alert alert-danger sort-error" style="display: none;">This did't save! Tell a dev please.</div>

app/views/admin/users/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Users</h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">

      <div class="box">
        <div class="box-body">

          <table id="example2" class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>

              <% @users.each do |user| %>
              <td><%= user.email %></td>
              <% end %>

            </tbody>
          </table>

        </div>
      </div>

    </div><!-- /.col -->
  </div><!-- /.row -->
</section><!-- /.content -->

app/views/contacts/new.html.erb
<h1>Contact</h1>

<%= simple_form_for(@contact) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :message %>
  <%= f.button :submit, value: "Submit" %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Lemon &amp; Basil Admin</title>
  <link rel="shortcut icon" href="/favicon.png?v=1.2">
  <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,500|Glass+Antiqua:100,200,300,400" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag 'admin' %>
  <%= javascript_include_tag 'admin' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin">
        <span class="green">lemon</span><span class="yellow">&amp;</span><span class="green">basil</span>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Pages", admin_pages_path %></li>
        <li><%= link_to "Menus", admin_categories_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text"><%= current_user.email %></p></li>
        <li><%= link_to "Logout", destroy_user_session_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">

  <% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Lemon &amp; Basil - Personal Chef</title>
  <link rel="shortcut icon" href="/favicon.png?v=1.2">
  <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,500|Glass+Antiqua:100,200,300,400" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <span class="logo">
          <span class="brand-name">
            <span class="green">lemon</span><span class="yellow">&amp;</span><span class="green">basil</span>
          </span>
          <span class="tag">Personal Chef Services</span>
        </span>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= nav_link "How it Works", how_it_works_path %></li>
        <li><%= nav_link "About", about_path %></li>
        <li><%= nav_link "Menus", menus_path %></li>
        <li><%= nav_link "Contact", new_contact_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

  <div id="content">
    <%= yield %>
  </div>
</div>

<footer>
  <div class="container">
    <h4>lemon&amp;basil</h4>
    <div>Chicago, IL 60622</div>
    <div>eat@lemonandbasil.co</div>
  </div>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36499930-11', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/pages/about.html.erb
<h1><%= @page.title %></h1>
<div class="image"><%= image_tag @page.image.url %></div>
<p><%= @page.body.html_safe %></p>

app/views/pages/home.html.erb
<div class="home">
  <div class="hero">
    <h1><%= @page.title %></h1>
    <h2><%= @page.tagline %></h2>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <div class="image"><%= image_tag @how_it_works.image.url %></div>
      <div class="link"><%= link_to "How it works", how_it_works_path, class: "btn" %></div>
    </div>
    <div class="col-sm-4">
      <div class="image"><%= image_tag @about.image.url %></div>
      <div class="link"><%= link_to "About me", about_path, class: "btn" %></div>
    </div>
    <div class="col-sm-4">
      <div class="image"><%= image_tag @menus.image.url %></div>
      <div class="link"><%= link_to "View menus", menus_path, class: "btn" %></div>
    </div>
  </div>

  <section>
    <q><%= @page.quote %></q>
    <cite><%= @page.quote_author %></cite>
  </section>
</div>

app/views/pages/how_it_works.html.erb
<h1><%= @page.title %></h1>
<div class="image"><%= image_tag @page.image.url %></div>
<p><%= @page.body.html_safe %></p>

app/views/pages/menus.html.erb
<h1><%= @page.title %></h1>
<% if @page.body.present? %>
<p><%= @page.body.html_safe %></p>
<% end %>

<div class="row">

  <div class="col-sm-3 categories-list">
    <% @categories.each_with_index do |category, index| %>
    <div class="category-name">
      <a href="" data-category-id="<%= category.id %>" class="<%= "active" if index === 0 %>"><%= category.name %></a>
    </div>
    <% end %>
  </div>

  <div class="col-sm-9 menu-items-list">
    <% @categories.each_with_index do |category, index| %>
      <div class="menu-items <%= "active" if index === 0 %>" data-category-id="<%= category.id %>">
      <% category.menu_items.each do |menu_item| %>
        <div class="menu-item">
          <div class="name"><%= menu_item.name %></div>
          <% if menu_item.description.present? %>
          <div class="description"><%= menu_item.description %></div>
          <% end %>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>

</div>

<%= javascript_tag do %>
  $(function(){
    new Menus();
  });
<% end %>